<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      // try:
      //  wrap suspicious code that may throw an error in try block.
      // The try statement allows us to define a block of code to be tested for errors while it is being executed.

      // catch:
      //  write code to do something in catch block when an error occurs.
      // The catch block can have parameters that will give you error information.
      // Catch block is used to log an error or display specific messages to the user.

      // finally:
      // finally block will always be executed regardless of the occurrence of an error.
      //  The finally block can be used to complete the remaining task or reset variables that might have changed before error occurred in try block.

      const throwErrorExampleFun = () => {
        let message;
        let x = prompt("Enter a number: ");
        try {
          if (x == "") throw "empty";
          if (isNaN(x)) throw "not a number";
          x = Number(x);
          if (x < 5) throw "too low";
          if (x > 10) throw "too high";
        } catch (err) {
          console.log(err);
        }
      };
      throwErrorExampleFun();

      try {
        let lastName = "Yetayeh";
        let fullName = fistName + " " + lastName;
      } catch (err) {
        console.log("Name of the error", err.name);
        console.log("Error message", err.message);
      } finally {
        console.log("In any case I will be executed");
      }
    </script>
  </body>
</html>
